epochs: 30
gene_dir: ./Liver/LIHC_cnv_rna_mut_sub_slide_scale_survival-v1.csv
img_dir: ./Liver/pt_file
best_model_path: ./gene_his_survival/Liver_LIHC_results
sur_ret_dir: ./gene_his_survival/Liver_LIHC_results
schedule: [10, 20, 30]
opt: adamw
decay_epochs: 10
opt_eps: 1.0e-8
opt_no_filter: False
sgd_no_nesterov: False
dyrep: False
sched: cosine
decay_rate: 0.1
decay_by_epoch: False

model_ema: False
model_ema_decay: 0.99996
warmup_epochs: 0
warmup_lr: 5.0e-7
batch_size: 8
lr: 2.0e-5
min_lr: 1.0e-5
lr_decay: 0.1
gpu_id: '3'
momentum: 0.9
weight_decay: 1.0e-5
classes: 4
train_ration: 0.8
#ce_surv nll_surv
bag_loss: 'nll_surv'
alpha_surv: 0.0
lambda_reg: 5.0e-6
task_type: survival